### ISSUE TITLE
Form contact details for profile 

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project#1]
# Value Proposition

**As a user 
**I need to fill in contact details 
**to be able to provide all important information to business partners**

# Description

<img width="271" alt="Screenshot 2022-05-09 at 12 44 28" src="https://user-images.githubusercontent.com/101577847/167395184-ba0affa5-8070-4db4-8961-2a32a1f32024.png">

# Acceptance Criteria

- [ ] All Inputs are required, show warning if empty.
- [ ] A submit button is required
- [ ] Input fields must be labeled  

# Tasks

(for developers team)

- [ ] Test is written for all input fields 
- [ ] Test is written for the submit button  
- [ ] Input fields are created for the topics first name, last name, phone number, e-mail, company name and the website    
- [ ] Input fields for "website" is labeled as a hyperlink 
- [ ] All fields except "website" are strings
- [ ] All information provided by the user are stored in the database

# Complexity
M
