### ISSUE TITLE
Start Screen

### ISSUE THREAD

**Issue by raimartontsch** [raimartontsch/capstone-project#3]
# Value Proposition

**As a** user I open the app. 
**I need** to access the different main features of the app fast 
**to be able to** choose the feature I need right now. 

# Description

<img width="235" alt="Screenshot 2022-05-09 at 12 58 55" src="https://user-images.githubusercontent.com/101577847/167396723-1367461c-62f1-4d9a-92ea-cf35e8951d40.png">

# Acceptance Criteria

- [ ] I see the logo of the web and now I picked the right app
- [ ] All main features the app provides are shown as icons
- [ ] All icons are show clearly the exact feature I am looking for
- [ ] Tapping a feature changes the color of the button and forwards me to the feature page 
- [ ] ...

# Tasks

(for developers team)

- [ ] The logo of the app is displayed on the start screen
- [ ] All main features are displayed as icons at the screen
- [ ] Main features are 1) show contact list 2) add contact 3) got to my profile page  
- [ ] Every icon can be tapped/clicked 
- [ ] On tap/click the icon changes its color 
- [ ] On tap/click the icon fowards the user to the feature  
- [ ] ...

# Complexity
M
